#!/usr/bin/env python
"""
build_odb.py - Reproducibly generate budget.odb (LibreOffice Base, embedded Firebird)
from the schema designed in personal_budget.ods.

Creates 5 tables (Accounts, Categories, Transactions, Budgets,
RecurringTransactions) with primary keys, foreign keys and CHECK constraints,
then seeds the relationally-complete reference data (all accounts + all
categories + the sample transactions/budgets/recurring rows).

Run with LibreOffice's bundled Python (it has the `uno` module):

    "C:\\Program Files\\LibreOffice\\program\\python.exe" scripts\\build_odb.py

The script spawns its own headless soffice on a private socket + user profile,
so it does not interfere with an interactive LibreOffice session.

Re-running overwrites budget.odb (pass --keep to abort if it already exists).
"""
import os
import sys
import time
import subprocess
import argparse


def log(msg):
    sys.stderr.write("[build_odb] %s\n" % msg)
    sys.stderr.flush()

# --- Reserved SQL words are quoted:  "date", "type", "month" -----------------

DDL = [
    """CREATE TABLE Accounts (
        id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        name             VARCHAR(50) NOT NULL,
        "type"           VARCHAR(20) NOT NULL,
        starting_balance DECIMAL(12,2) DEFAULT 0.00 NOT NULL,
        CONSTRAINT chk_acct_type CHECK ("type" IN ('Checking','Savings','Credit','Investment'))
    )""",
    """CREATE TABLE Categories (
        id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        name               VARCHAR(50) NOT NULL,
        parent_category_id INTEGER,
        kind               VARCHAR(10),
        CONSTRAINT fk_cat_parent FOREIGN KEY (parent_category_id) REFERENCES Categories(id),
        CONSTRAINT chk_cat_kind  CHECK (kind IN ('Income','Expense'))
    )""",
    """CREATE TABLE Transactions (
        id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        "date"      DATE NOT NULL,
        account_id  INTEGER,
        category_id INTEGER,
        amount      DECIMAL(12,2) NOT NULL,
        description VARCHAR(255),
        "type"      VARCHAR(10),
        CONSTRAINT fk_txn_acct FOREIGN KEY (account_id)  REFERENCES Accounts(id),
        CONSTRAINT fk_txn_cat  FOREIGN KEY (category_id) REFERENCES Categories(id),
        CONSTRAINT chk_txn_type CHECK ("type" IN ('Income','Expense'))
    )""",
    """CREATE TABLE Budgets (
        id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        category_id    INTEGER,
        "month"        DATE NOT NULL,
        planned_amount DECIMAL(12,2) NOT NULL,
        CONSTRAINT fk_bud_cat FOREIGN KEY (category_id) REFERENCES Categories(id),
        CONSTRAINT uq_bud_cat_month UNIQUE (category_id, "month")
    )""",
    """CREATE TABLE RecurringTransactions (
        id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        description   VARCHAR(255) NOT NULL,
        amount        DECIMAL(12,2) NOT NULL,
        frequency     VARCHAR(20) NOT NULL,
        category_id   INTEGER,
        account_id    INTEGER,
        next_due_date DATE NOT NULL,
        CONSTRAINT fk_rec_cat  FOREIGN KEY (category_id) REFERENCES Categories(id),
        CONSTRAINT fk_rec_acct FOREIGN KEY (account_id) REFERENCES Accounts(id),
        CONSTRAINT chk_rec_freq CHECK (frequency IN ('Daily','Weekly','Monthly','Yearly'))
    )""",
]

# --- Seed data (ids match personal_budget.ods schema sheets) ------------------

ACCOUNTS = [
    (1, 'Checking', 'Checking', 2500.00),
    (2, 'Savings', 'Savings', 8000.00),
    (3, 'Visa Credit Card', 'Credit', -450.00),
    (4, 'Brokerage', 'Investment', 15000.00),
]

CATEGORIES = [
    (1, 'Income', None, 'Income'),
    (2, 'Salary', 1, 'Income'),
    (3, 'Freelance', 1, 'Income'),
    (4, 'Investments', 1, 'Income'),
    (5, 'Other Income', 1, 'Income'),
    (6, 'Expenses', None, 'Expense'),
    (7, 'Housing (Rent/Mortgage)', 6, 'Expense'),
    (8, 'Utilities', 6, 'Expense'),
    (9, 'Groceries', 6, 'Expense'),
    (10, 'Transportation', 6, 'Expense'),
    (11, 'Insurance', 6, 'Expense'),
    (12, 'Healthcare', 6, 'Expense'),
    (13, 'Dining Out', 6, 'Expense'),
    (14, 'Entertainment', 6, 'Expense'),
    (15, 'Clothing', 6, 'Expense'),
    (16, 'Subscriptions', 6, 'Expense'),
    (17, 'Savings/Investments', 6, 'Expense'),
    (18, 'Miscellaneous', 6, 'Expense'),
]

TRANSACTIONS = [
    (1, '2026-01-04', 1, 3, 337.37, 'Freelance Payment - Client A', 'Income'),
    (2, '2026-01-06', 3, 14, 24.27, 'Movie Tickets', 'Expense'),
    (3, '2026-01-11', 1, 13, 10.88, 'Coffee Shop', 'Expense'),
    (4, '2026-01-17', 1, 16, 15.00, 'Netflix', 'Expense'),
    (5, '2026-01-22', 3, 9, 111.91, 'Whole Foods', 'Expense'),
    (6, '2026-01-29', 1, 7, 1200.00, 'Rent Payment', 'Expense'),
    (7, '2026-02-07', 1, 2, 3200.00, 'Direct Deposit - Employer', 'Income'),
]

BUDGETS = [
    (1, 7, '2026-01-01', 1200.00),
    (2, 8, '2026-01-01', 120.00),
    (3, 9, '2026-01-01', 150.00),
    (4, 13, '2026-01-01', 60.00),
    (5, 14, '2026-01-01', 50.00),
]

RECURRING = [
    (1, 'Rent Payment', 1200.00, 'Monthly', 7, 1, '2026-08-01'),
    (2, 'Netflix', 15.00, 'Monthly', 16, 1, '2026-08-10'),
    (3, 'Spotify', 10.00, 'Monthly', 16, 1, '2026-08-05'),
    (4, 'Salary Deposit', 3200.00, 'Monthly', 2, 1, '2026-08-07'),
    (5, 'Health Insurance Premium', 320.00, 'Monthly', 11, 1, '2026-08-12'),
]


def q(v):
    """Render a Python value as a Firebird SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    return str(v)


def seed_statements():
    stmts = []
    for r in ACCOUNTS:
        stmts.append('INSERT INTO Accounts (id,name,"type",starting_balance) VALUES (%s)'
                     % ",".join(q(x) for x in r))
    for r in CATEGORIES:
        stmts.append('INSERT INTO Categories (id,name,parent_category_id,kind) VALUES (%s)'
                     % ",".join(q(x) for x in r))
    for r in TRANSACTIONS:
        stmts.append('INSERT INTO Transactions (id,"date",account_id,category_id,amount,description,"type") VALUES (%s)'
                     % ",".join(q(x) for x in r))
    for r in BUDGETS:
        stmts.append('INSERT INTO Budgets (id,category_id,"month",planned_amount) VALUES (%s)'
                     % ",".join(q(x) for x in r))
    for r in RECURRING:
        stmts.append('INSERT INTO RecurringTransactions (id,description,amount,frequency,category_id,account_id,next_due_date) VALUES (%s)'
                     % ",".join(q(x) for x in r))
    # Advance IDENTITY sequences past the explicit ids we inserted.
    stmts += [
        "ALTER TABLE Accounts ALTER COLUMN id RESTART WITH %d" % (len(ACCOUNTS) + 1),
        "ALTER TABLE Categories ALTER COLUMN id RESTART WITH %d" % (len(CATEGORIES) + 1),
        "ALTER TABLE Transactions ALTER COLUMN id RESTART WITH %d" % (len(TRANSACTIONS) + 1),
        "ALTER TABLE Budgets ALTER COLUMN id RESTART WITH %d" % (len(BUDGETS) + 1),
        "ALTER TABLE RecurringTransactions ALTER COLUMN id RESTART WITH %d" % (len(RECURRING) + 1),
    ]
    return stmts


# --- UNO plumbing ------------------------------------------------------------

SOFFICE = r"C:\Program Files\LibreOffice\program\soffice.bin"
PORT = 2103
PROFILE = "file:///c:/temp/lo_odb_build"


def connect(ctx_local):
    import uno
    resolver = ctx_local.ServiceManager.createInstanceWithContext(
        "com.sun.star.bridge.UnoUrlResolver", ctx_local)
    url = ("uno:socket,host=localhost,port=%d;urp;StarOffice.ComponentContext" % PORT)
    last = None
    for _ in range(60):
        try:
            return resolver.resolve(url)
        except Exception as e:  # NoConnectException until soffice is ready
            last = e
            time.sleep(0.5)
    raise RuntimeError("Could not connect to soffice: %s" % last)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--odb", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "budget.odb"))
    ap.add_argument("--keep", action="store_true",
                    help="abort if the .odb already exists instead of overwriting")
    args = ap.parse_args()

    import uno
    from com.sun.star.beans import PropertyValue  # noqa: F401 (validates bridge)

    odb_path = os.path.abspath(args.odb)
    if os.path.exists(odb_path):
        if args.keep:
            print("Refusing to overwrite existing %s (--keep)" % odb_path)
            return 1
        os.remove(odb_path)
    odb_url = uno.systemPathToFileUrl(odb_path)

    log("spawning soffice on port %d" % PORT)
    proc = subprocess.Popen([
        SOFFICE, "--headless", "--norestore", "--invisible", "--nologo",
        "--nofirststartwizard", "-env:UserInstallation=" + PROFILE,
        "--accept=socket,host=localhost,port=%d;urp;StarOffice.ServiceManager" % PORT,
    ])
    try:
        local = uno.getComponentContext()
        log("connecting...")
        ctx = connect(local)
        log("connected")
        smgr = ctx.ServiceManager

        db_context = smgr.createInstanceWithContext(
            "com.sun.star.sdb.DatabaseContext", ctx)
        data_source = db_context.createInstance()
        data_source.URL = "sdbc:embedded:firebird"
        db_doc = data_source.DatabaseDocument
        log("storeAsURL %s" % odb_url)
        db_doc.storeAsURL(odb_url, ())

        log("getConnection (embedded firebird)...")
        conn = data_source.getConnection("", "")
        log("got connection; running DDL")
        stmt = conn.createStatement()

        for sql in DDL:
            stmt.execute(sql)
        log("DDL done; seeding")
        for sql in seed_statements():
            stmt.execute(sql)
        log("seed done; storing")

        # Persist the embedded Firebird database back into the .odb package.
        db_doc.store()
        conn.close()
        db_doc.close(False)
        log("stored and closed")
        print("Created %s" % odb_path)
        return 0
    finally:
        try:
            desktop = smgr.createInstanceWithContext(
                "com.sun.star.frame.Desktop", ctx)
            desktop.terminate()
        except Exception:
            pass
        try:
            proc.wait(timeout=20)
        except Exception:
            proc.terminate()


if __name__ == "__main__":
    sys.exit(main())
